### ISSUE TITLE
Choose one voting library to start with

### ISSUE THREAD

**Issue by subjective** [democracy/voting#1]
* Investigate how we might be able to use these functionalities (API? Open source? Centralized service?)
* Contribute to the [spreadsheet](https://docs.google.com/a/berkeley.edu/spreadsheets/d/1QMworJzHaiqDbPf4uX0WYJ4Z-ddnkrPTMrUmBNAcLGs/edit#gid=1660122072)

**Comment by subjective** [comment]
https://github.com/bradbeattie/python-vote-core
https://github.com/agoravoting/agora-ciudadana
http://pythonhosted.org//ballotbox/

**Comment by jamesholston** [comment]
This issue was moved to socialappslab/appcivist-voting#1

**Comment by cdparra** [comment]
This issue was moved to socialappslab/appcivist-voting#2
