### ISSUE TITLE
Make pro/con list of types of voting

### ISSUE THREAD

**Issue by subjective** [democracy/voting#3]
* Arguments for and against each type of voting
* Which is more fair?
* Hypothetical situations, e.g., few people? More than 1000 people?
* Research analyses of the use of different voting systems in social movements and organizations

**Comment by maxgrunberg** [comment]
Unranked 


-	Pros
o	one person, one vote (simple)
o	Moderation (no extremist positions)

-	Cons

o	Tactical voting → compromising: "All votes for anyone other than the second place are votes for the winner"
o	A lot of power is given to the media
o	The system may promote votes against more so than votes for and will probably result in a two proposal system
o	Wasted votes
o	Spoiler effect (split of votes between two similiar proposals)
o	Risk of the focus on a certain proposal, not much need to read the other proposals, if you have a favorite proposal from the beginning


Ranked/distribution

-	Pros
o	Consensual, more democraic?
o	closer analysis of the different options
o	Resistance to tactical voting
o	Uniqueness of votes


-	Cons
o	 spoiler effect, even stronger than in the unranked

**Comment by cdparra** [comment]
This issue was moved to socialappslab/appcivist-voting#6
